const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.connectOverCDP('http://127.0.0.1:9333');const pages=b.contexts()[0].pages();let p;for(const page of pages)if((await page.title()).includes('agy-2.2-dev-acceptance'))p=page;if(!p)throw Error('Own acceptance window missing');const r={version:'2.2.0',environment:'Windows VS Code + WSL development host, actual agy 1.2.14',steps:[]};
try{
r.title=await p.title();await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Developer: Reload Window');await p.keyboard.press('Enter');await p.waitForTimeout(6000);
await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Antigravity: Open Chat Sidebar');await p.keyboard.press('Enter');
let f;for(let i=0;i<60&&!f;i++){for(const frame of p.frames())if(await frame.locator('#message-input').count())f=frame;if(!f)await p.waitForTimeout(500);}if(!f)throw Error('No Webview');
await f.waitForFunction(()=>document.querySelector('#session-select')?.value && !document.querySelector('#new-session-btn').disabled);
if(await f.locator('.message').count()){await f.locator('#new-session-btn').click();await f.waitForFunction(()=>!document.querySelectorAll('.message').length);}
async function slash(text){await f.locator('#message-input').fill(text);await f.locator('#send-btn').click();await f.waitForFunction(()=>!document.querySelector('#message-input').value,{},{timeout:180000});}
await slash('/help');assert((await f.locator('.command-output').innerText()).includes('/plan'));assert.equal(await f.locator('.message').count(),0);r.steps.push('help local, zero model messages');
await slash('/model');assert.equal(await f.locator('#model-select option').count(),11);r.steps.push('11 native model IDs');
await f.locator('#message-input').fill('/effort max');await f.locator('#send-btn').click();await f.locator('[role=alert]').filter({hasText:'max'}).waitFor();assert.equal(await f.locator('#effort-select').count(),0);r.steps.push('max correctly rejected for suffixed Gemini');
await slash('/workspace');assert((await f.locator('.command-output').innerText()).includes('agy-2.2-dev-acceptance'));r.steps.push('workspace/config report');
await slash('/skills');assert((await f.locator('.command-output').innerText()).includes('parity-window'));await slash('/parity-window');await f.locator('.assistant').filter({hasText:'SKILL_WINDOW220'}).waitFor({timeout:180000});await f.locator('#send-btn').waitFor();const history=await f.locator('#session-select').inputValue();r.steps.push('real native skill response');
await slash('/open "open-target.txt:2"');await p.locator('.tab.active').filter({hasText:'open-target.txt'}).waitFor();r.steps.push('slash opens workspace file');
await slash('/new');await f.waitForFunction(id=>document.querySelector('#session-select').value!==id,history);assert.equal(await f.locator('.message').count(),0);
await slash('/plan 给一个极简只读方案，回答 PLAN_WINDOW220。不要读取文件、执行工具或修改文件。只输出方案，等待批准。');await f.locator('#approve-plan-btn').waitFor({timeout:180000});assert.equal(await f.locator('#mode-select').inputValue(),'plan');r.steps.push('plan output waits for approval');
await slash('/approve');await f.locator('#mode-select').filter({has: f.locator('option')}).waitFor();await f.waitForFunction(()=>document.querySelector('#mode-select').value==='normal' && document.querySelectorAll('.assistant').length>=2 && !document.querySelector('#stop-btn'),{},{timeout:180000});r.steps.push('slash approve executes');
await slash('/history '+history);await f.locator('.assistant').filter({hasText:'SKILL_WINDOW220'}).waitFor();r.steps.push('history restored');
await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Developer: Reload Window');await p.keyboard.press('Enter');await p.waitForTimeout(6000);await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Antigravity: Open Chat Sidebar');await p.keyboard.press('Enter');f=undefined;for(let i=0;i<40&&!f;i++){for(const frame of p.frames())if(await frame.locator('#message-input').count())f=frame;if(!f)await p.waitForTimeout(500);}if(!f)throw Error('No restored Webview');await f.locator('.assistant').filter({hasText:'SKILL_WINDOW220'}).waitFor();r.steps.push('reload history recovery');
r.passed=true;await p.screenshot({path:'C:/Users/Public/agy-2-acceptance/2.2-dev.png'});
}catch(e){r.passed=false;r.error=e.stack;await p.screenshot({path:'C:/Users/Public/agy-2-acceptance/2.2-dev-error.png'}).catch(()=>{});}finally{fs.writeFileSync('C:/Users/Public/agy-2-acceptance/2.2-dev.json',JSON.stringify(r,null,2));console.log(r);if(r.passed)await p.close();await b.close();if(!r.passed)process.exitCode=1;}
})();
