const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.connectOverCDP('http://127.0.0.1:9333');let p;for(const q of b.contexts()[0].pages())if((await q.title()).includes('agy-2.2-installed-acceptance'))p=q;if(!p)throw Error('Own installed window missing');const r={version:'2.2.0',environment:'ordinary Windows VS Code + WSL installed extension',steps:[]};
try{await p.bringToFront();r.title=await p.title();assert(!r.title.includes('Extension Development'));await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Antigravity: Open Chat Sidebar');await p.keyboard.press('Enter');let f;for(let i=0;i<60&&!f;i++){for(const q of p.frames())if(await q.locator('#message-input').count()&&await q.locator('#message-input').isVisible())f=q;if(!f)await p.waitForTimeout(500);}if(!f)throw Error('Missing webview');
r.scripts=await f.locator('script[src]').evaluateAll(nodes=>nodes.map(n=>n.src));assert(r.scripts.some(s=>s.includes('antigravity-vscode-extender-2.2.0')));r.steps.push('actual installed 2.2.0 bundle loaded');await f.waitForFunction(()=>document.querySelector('#session-select')?.value&&!document.querySelector('#new-session-btn').disabled);await p.waitForTimeout(1000);
async function slash(text){await f.locator('#message-input').fill(text);await f.waitForFunction(t=>document.querySelector('#message-input').value===t&&!document.querySelector('#send-btn').disabled,text);await f.locator('#message-input').press('Enter');await f.waitForFunction(()=>!document.querySelector('#message-input').value,{},{timeout:180000});await p.waitForTimeout(250);}
await slash('/help');assert((await f.locator('.command-output').innerText()).includes('/schema'));assert.equal(await f.locator('.message').count(),0);r.steps.push('local help, no model messages');await slash('/model');assert.equal(await f.locator('#model-select option').count(),11);r.steps.push('11 native models');await slash('/workspace');assert((await f.locator('.command-output').innerText()).includes('agy-2.2-installed-acceptance'));r.steps.push('workspace report');await slash('/skills');assert((await f.locator('.command-output').innerText()).includes('parity-installed'));await slash('/parity-installed');await f.locator('.assistant').filter({hasText:'SKILL_INSTALLED220'}).waitFor({timeout:180000});await f.waitForFunction(()=>!document.querySelector('#stop-btn'));const id=await f.locator('#session-select').inputValue();r.originalSessionId=id;r.steps.push('native skill execution');await slash('/open "open-target.txt:2"');await p.locator('.tab.active').filter({hasText:'open-target.txt'}).waitFor();r.steps.push('file open');await slash('/new');assert.notEqual(await f.locator('#session-select').inputValue(),id);assert.equal(await f.locator('.message').count(),0);await slash('/history '+id);await f.locator('.assistant').filter({hasText:'SKILL_INSTALLED220'}).waitFor();r.steps.push('new and history restore');
await slash('/cli');await f.waitForFunction(id=>document.querySelector('#session-select').value!==id,id);await p.locator('.terminal').first().waitFor();r.steps.push('idle native handoff creates terminal and separate draft');await p.screenshot({path:'C:/Users/Public/agy-2-acceptance/2.2-installed-handoff.png'});
await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Terminal: Kill the Active Terminal Instance');await p.keyboard.press('Enter');await p.waitForTimeout(1500);await slash('/history '+id);await slash('/history sync');r.steps.push('closed own terminal and synced original history');
await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Developer: Reload Window');await p.keyboard.press('Enter');await p.waitForTimeout(6000);await p.keyboard.press('Control+Shift+P');await p.locator('.quick-input-widget input').fill('>Antigravity: Open Chat Sidebar');await p.keyboard.press('Enter');f=undefined;for(let i=0;i<50&&!f;i++){for(const q of p.frames())if(await q.locator('#message-input').count()&&await q.locator('#message-input').isVisible())f=q;if(!f)await p.waitForTimeout(300);}if(!f)throw Error('No reloaded webview');await f.locator('.assistant').filter({hasText:'SKILL_INSTALLED220'}).waitFor();await p.waitForTimeout(1000);await slash('/help');r.steps.push('installed reload, history and commands restored');r.passed=true;await p.screenshot({path:'C:/Users/Public/agy-2-acceptance/2.2-installed.png'});
}catch(e){r.passed=false;r.error=e.stack;await p.screenshot({path:'C:/Users/Public/agy-2-acceptance/2.2-installed-error.png'}).catch(()=>{});}finally{fs.writeFileSync('C:/Users/Public/agy-2-acceptance/2.2-installed.json',JSON.stringify(r,null,2));console.log(r);if(r.passed)await p.close();await b.close();if(!r.passed)process.exitCode=1;}})();